### ISSUE TITLE
Initializing a job without walltime creates an error in submit

### ISSUE THREAD

**Issue by soungalo** [MayroseLab/pbs#2]
Initializing a job without walltime is allowed (and it should be), which leaves it a "None" value and when job.submit() is called, an error is thrown:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pbs/job.py", line 236, in submit
    walltime=misc.seconds(self.walltime),
  File "pbs/misc.py", line 72, in seconds
    wtime = walltime.split(":")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by soungalo** [comment]
Resolved in PR #9
