### ISSUE TITLE
pstat crashes on ValueError

### ISSUE THREAD

**Issue by soungalo** [MayroseLab/pbs#4]
```
$ python scripts/pstat

Traceback (most recent call last):
  File "scripts/pstat", line 328, in <module>
    main()
  File "scripts/pstat", line 273, in main
    db.update()
  File "/groups/itay_mayrose/liorglic/.local/lib/python2.7/site-packages/pbs/jobdb.py", line 368, in update
    active_status = misc_pbs.job_status()
  File "/groups/itay_mayrose/liorglic/.local/lib/python2.7/site-packages/pbs/misc_torque.py", line 138, in job_status
    stdout = _qstat(jobid=jobid, full=True)
  File "/groups/itay_mayrose/liorglic/.local/lib/python2.7/site-packages/pbs/misc_torque.py", line 23, in _qstat
    if full and username is not None and int(version.split('.')[0]) < 5 and jobid is None:
ValueError: invalid literal for int() with base 10: 'pbs_version = 14'
```

**Comment by soungalo** [comment]
Fixed by PR #5
